services:
  engine:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: autopatch_forge_engine

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - .:/app
      - ~/.ssh:/root/.ssh:ro

    restart: unless-stopped