services:
  engine:
    build: .
    container_name: autopatch_forge_engine

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - .:/app

      # SSH for GitHub automation
      - ~/.ssh:/root/.ssh:ro

    restart: unless-stopped